Imports System
Imports System.Windows.Forms
Imports DevExpress.DataAccess.UI.Sql

Namespace WinFormsSqlDataSource
    Partial Public Class Form1
        Inherits Form

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            ' Fill a SqlDataSource
            sqlDataSource1.Fill()
        End Sub

        Private Sub button1_Click(ByVal sender As Object, ByVal e As EventArgs) Handles button1.Click
            If sqlDataSource1.Queries(0).EditQuery() Then
                sqlDataSource1.Fill()

                Me.gridView1.Columns.Clear()

                Me.gridControl1.DataSource = Nothing
                Me.gridControl1.DataMember = Nothing

                Me.gridControl1.DataSource = sqlDataSource1
                Me.gridControl1.DataMember = sqlDataSource1.Queries(0).Name
            End If
        End Sub
    End Class
End Namespace
